/**
 * App Store review: one-time demo data for a dedicated reviewer account only.
 * No UI surfaces this; gated by authenticated email + empty account + per-user flag in local settings.
 */

import { getDB, generateId, getNow, getToday, addDays } from "@/lib/storage/db";
import { getSettings, updateSettings } from "@/lib/storage/settings";
import type { CareEvent, Clutch, Pairing, Reptile, ScheduleItem, DietType } from "@/types";

/** Reviewer account — must match Supabase Auth email exactly after normalization. */
export const APPLE_REVIEW_DEMO_EMAIL = "demo.reptilita@gmail.com";

const SAMPLE_NOTE = "(Sample data for App Store review.)";

/** Paste into App Review notes or App Store Connect; not shown in-app. */
export const APPLE_REVIEW_NOTES_FOR_APP_STORE = [
  "Demo account: sign in with demo.reptilita@gmail.com (credentials provided separately to App Review).",
  "On first sign-in with an empty library, the app automatically adds three sample animals (two Ball Pythons plus a White's Tree Frog), care schedules, journal entries, and a planned breeding pairing example.",
  "No hidden gestures or reviewer-only UI—the flow uses the standard build; seeding is keyed to this email once per device user id.",
  "Seeded reptiles and care tasks sync with Supabase using the normal path; pairing/clutch sample data is stored locally for now.",
].join(" ");

function normalizeEmail(email: string | undefined): string {
  return (email ?? "").trim().toLowerCase();
}

function getFeedFreq(dietType: DietType): number {
  switch (dietType) {
    case "insects":
      return 2;
    case "rodents":
      return 7;
    case "mixed":
      return 3;
    case "fish":
      return 3;
    case "herbivore":
      return 1;
    case "omnivore":
      return 3;
    case "pellets":
      return 2;
    default:
      return 5;
  }
}

function defaultSchedules(reptileId: string, dietType: DietType, today: string, ts: string): ScheduleItem[] {
  const feedFreq = getFeedFreq(dietType);
  return [
    {
      id: generateId(),
      reptileId,
      taskType: "feed",
      frequencyDays: feedFreq,
      lastDoneDate: addDays(today, -feedFreq + 2),
      nextDueDate: addDays(today, 1),
      autoGenerated: true,
      updatedAt: ts,
    },
    {
      id: generateId(),
      reptileId,
      taskType: "clean",
      frequencyDays: 14,
      lastDoneDate: addDays(today, -10),
      nextDueDate: addDays(today, 4),
      autoGenerated: true,
      updatedAt: ts,
    },
    {
      id: generateId(),
      reptileId,
      taskType: "check",
      frequencyDays: 7,
      lastDoneDate: addDays(today, -5),
      nextDueDate: today,
      autoGenerated: true,
      updatedAt: ts,
    },
  ];
}

async function accountIsEligibleForFreshSeed(): Promise<boolean> {
  const db = await getDB();
  const [reptiles, schedules, events] = await Promise.all([
    db.getAll("reptiles"),
    db.getAll("scheduleItems"),
    db.getAll("careEvents"),
  ]);
  return reptiles.length === 0 && schedules.length === 0 && events.length === 0;
}

/**
 * Seeds IndexedDB once for the reviewer account when the store is empty.
 * Caller must sync reptiles/tasks to Supabase afterward.
 * @returns true if seed ran
 */
export async function trySeedAppleReviewDemoForSession(
  userId: string,
  emailFromSession: string | undefined,
): Promise<boolean> {
  if (normalizeEmail(emailFromSession) !== normalizeEmail(APPLE_REVIEW_DEMO_EMAIL)) {
    return false;
  }

  const settings = await getSettings();
  const prior = settings.appleReviewDemoSeededUserIds ?? [];
  if (prior.includes(userId)) {
    return false;
  }

  if (!(await accountIsEligibleForFreshSeed())) {
    return false;
  }

  const db = await getDB();
  const now = getNow();
  const today = getToday();

  const orion: Reptile = {
    id: generateId(),
    name: "Orion",
    species: "Ball Python",
    commonName: "Ball Python",
    scientificName: "Python regius",
    animalClass: "reptile",
    animalCategory: "snake",
    speciesGroup: "Python",
    morph: "Mojave",
    sex: "male",
    birthDate: "2021-04-12",
    dietType: "rodents",
    breedingStatus: "breeder",
    notes: `Reliable eater on frozen-thawed rats. ${SAMPLE_NOTE}`,
    habitatType: "terrestrial",
    humidityPreference: "moderate",
    uvbRequirement: "optional",
    waterRequirement: "bowl",
    handlingProfile: "calm",
    sortOrder: 0,
    createdAt: now,
    updatedAt: now,
  };

  const vega: Reptile = {
    id: generateId(),
    name: "Vega",
    species: "Ball Python",
    commonName: "Ball Python",
    scientificName: "Python regius",
    animalClass: "reptile",
    animalCategory: "snake",
    speciesGroup: "Python",
    morph: "Normal",
    sex: "female",
    birthDate: "2020-09-01",
    dietType: "rodents",
    breedingStatus: "breeder",
    notes: `Good body condition; cooling planned per season. ${SAMPLE_NOTE}`,
    habitatType: "terrestrial",
    humidityPreference: "moderate",
    uvbRequirement: "optional",
    waterRequirement: "bowl",
    handlingProfile: "tolerant",
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  };

  const pip: Reptile = {
    id: generateId(),
    name: "Pip",
    species: "White's Tree Frog",
    commonName: "White's Tree Frog",
    scientificName: "Ranoidea caerulea",
    animalClass: "amphibian",
    animalCategory: "frog",
    speciesGroup: "Tree Frog",
    morph: "Blue-phase (example)",
    sex: "unknown",
    estimatedAgeMonths: 18,
    dietType: "insects",
    breedingStatus: "pet",
    notes: `Dusted crickets; misted enclosure daily. Substrate refreshed on schedule. ${SAMPLE_NOTE}`,
    habitatType: "arboreal",
    humidityPreference: "high",
    uvbRequirement: "optional",
    waterRequirement: "bowl",
    handlingProfile: "tolerant",
    isAmphibian: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  };

  const reptiles: Reptile[] = [orion, vega, pip];

  await Promise.all(reptiles.map((r) => db.put("reptiles", r)));

  const schedules: ScheduleItem[] = [
    ...defaultSchedules(orion.id, orion.dietType, today, now),
    ...defaultSchedules(vega.id, vega.dietType, today, now),
    ...defaultSchedules(pip.id, pip.dietType, today, now),
  ];
  for (const s of schedules) {
    await db.put("scheduleItems", s);
  }

  const journalNotes: CareEvent[] = [
    {
      id: generateId(),
      reptileId: orion.id,
      eventType: "note",
      eventDate: addDays(today, -3),
      details: `Weighed and recorded shedding notes. Husbandry checklist completed. ${SAMPLE_NOTE}`,
      createdAt: now,
    },
    {
      id: generateId(),
      reptileId: pip.id,
      eventType: "note",
      eventDate: addDays(today, -1),
      details: `Replaced moss, verified humidity gradient. ${SAMPLE_NOTE}`,
      createdAt: now,
    },
  ];

  const extraEvents: CareEvent[] = [
    {
      id: generateId(),
      reptileId: vega.id,
      eventType: "feeding",
      eventDate: addDays(today, -7),
      details: `Small rat (~10% body weight). ${SAMPLE_NOTE}`,
      supplements: ["calcium"],
      createdAt: now,
    },
  ];

  for (const e of [...journalNotes, ...extraEvents]) {
    await db.put("careEvents", e);
  }

  const pairing: Pairing = {
    id: generateId(),
    parentAId: orion.id,
    parentBId: vega.id,
    startDate: addDays(today, -30),
    status: "planned",
    notes: `Example pairing record for demonstration. Confirm pairing suitability with species-specific guidelines. ${SAMPLE_NOTE}`,
    createdAt: now,
  };

  const clutch: Clutch = {
    id: generateId(),
    pairingId: pairing.id,
    laidDate: addDays(today, -14),
    eggCount: 6,
    incubatorNotes: `Example incubator entry only—no live eggs implied. ${SAMPLE_NOTE}`,
    expectedHatchDate: addDays(today, 40),
    createdAt: now,
  };

  await db.put("pairings", pairing);
  await db.put("clutches", clutch);

  await updateSettings({
    appleReviewDemoSeededUserIds: [...prior, userId],
  });

  return true;
}
