// Demo data for testing
import { getDB, generateId, getToday, addDays, getNow } from './db';
import type { Reptile, CareEvent, ScheduleItem } from '@/types';

export async function loadDemoData(): Promise<void> {
  const db = await getDB();
  
  // Check if data already exists
  const existingReptiles = await db.getAll('reptiles');
  if (existingReptiles.length > 0) {
    // Clear existing data first
    await clearAllData();
  }

  const now = getNow();
  const today = getToday();

  // Create demo reptiles with Phase 2 genetics fields
  const draco: Reptile = {
    id: generateId(),
    name: 'Draco',
    species: 'Ball Python',
    morph: 'Pastel',
    sex: 'male',
    birthDate: '2022-03-15',
    dietType: 'rodents',
    breedingStatus: 'breeder',
    acquisitionDate: '2022-06-01',
    notes: 'Very calm, great eater. Prefers rats over mice.',
    hets: ['clown', 'pied'],
    geneticsNotes: 'Proven breeder, 100% het clown from proven pairing.',
    createdAt: now,
    updatedAt: now,
  };

  const ember: Reptile = {
    id: generateId(),
    name: 'Ember',
    species: 'Leopard Gecko',
    morph: 'Tangerine',
    sex: 'female',
    estimatedAgeMonths: 18,
    dietType: 'insects',
    breedingStatus: 'pet',
    acquisitionDate: '2023-08-20',
    notes: 'Active at dusk. Loves dubia roaches.',
    createdAt: now,
    updatedAt: now,
  };

  const nova: Reptile = {
    id: generateId(),
    name: 'Nova',
    species: 'Ball Python',
    morph: 'Piebald',
    sex: 'female',
    birthDate: '2021-08-10',
    dietType: 'rodents',
    breedingStatus: 'breeder',
    acquisitionDate: '2022-02-14',
    notes: 'Beautiful high-white pied. Great temperament.',
    hets: [],
    geneticsNotes: 'Visual piebald, unknown hets.',
    createdAt: now,
    updatedAt: now,
  };

  // Save reptiles
  await db.put('reptiles', draco);
  await db.put('reptiles', ember);
  await db.put('reptiles', nova);

  // Create schedule items for Draco (rodents = 7 day feeding)
  const dracoSchedule: ScheduleItem[] = [
    {
      id: generateId(),
      reptileId: draco.id,
      taskType: 'feed',
      frequencyDays: 7,
      lastDoneDate: addDays(today, -5),
      nextDueDate: addDays(today, 2),
      autoGenerated: true,
    },
    {
      id: generateId(),
      reptileId: draco.id,
      taskType: 'clean',
      frequencyDays: 14,
      lastDoneDate: addDays(today, -10),
      nextDueDate: addDays(today, 4),
      autoGenerated: true,
    },
    {
      id: generateId(),
      reptileId: draco.id,
      taskType: 'check',
      frequencyDays: 7,
      lastDoneDate: addDays(today, -7),
      nextDueDate: today, // Due today!
      autoGenerated: true,
    },
  ];

  // Create schedule items for Ember (insects = 2 day feeding)
  const emberSchedule: ScheduleItem[] = [
    {
      id: generateId(),
      reptileId: ember.id,
      taskType: 'feed',
      frequencyDays: 2,
      lastDoneDate: addDays(today, -3),
      nextDueDate: addDays(today, -1), // Overdue!
      autoGenerated: true,
    },
    {
      id: generateId(),
      reptileId: ember.id,
      taskType: 'clean',
      frequencyDays: 14,
      lastDoneDate: addDays(today, -12),
      nextDueDate: addDays(today, 2),
      autoGenerated: true,
    },
    {
      id: generateId(),
      reptileId: ember.id,
      taskType: 'check',
      frequencyDays: 7,
      lastDoneDate: addDays(today, -5),
      nextDueDate: addDays(today, 2),
      autoGenerated: true,
    },
  ];

  // Create schedule items for Nova
  const novaSchedule: ScheduleItem[] = [
    {
      id: generateId(),
      reptileId: nova.id,
      taskType: 'feed',
      frequencyDays: 7,
      lastDoneDate: addDays(today, -3),
      nextDueDate: addDays(today, 4),
      autoGenerated: true,
    },
    {
      id: generateId(),
      reptileId: nova.id,
      taskType: 'clean',
      frequencyDays: 14,
      lastDoneDate: addDays(today, -8),
      nextDueDate: addDays(today, 6),
      autoGenerated: true,
    },
    {
      id: generateId(),
      reptileId: nova.id,
      taskType: 'check',
      frequencyDays: 7,
      lastDoneDate: addDays(today, -2),
      nextDueDate: addDays(today, 5),
      autoGenerated: true,
    },
  ];

  // Save schedules
  for (const item of [...dracoSchedule, ...emberSchedule, ...novaSchedule]) {
    await db.put('scheduleItems', item);
  }

  // Create some demo care events with Phase 1.5 features
  const events: CareEvent[] = [
    {
      id: generateId(),
      reptileId: draco.id,
      eventType: 'feeding',
      eventDate: addDays(today, -5),
      details: 'Fed one medium rat. Ate immediately.',
      supplements: ['calcium'],
      createdAt: now,
    },
    {
      id: generateId(),
      reptileId: draco.id,
      eventType: 'shedding',
      eventDate: addDays(today, -12),
      details: 'Complete shed, one piece. Healthy skin.',
      createdAt: now,
    },
    {
      id: generateId(),
      reptileId: draco.id,
      eventType: 'health',
      eventDate: addDays(today, -20),
      details: 'Weight check. Looking good!',
      weightGrams: 1850,
      lengthCm: 120,
      createdAt: now,
    },
    {
      id: generateId(),
      reptileId: ember.id,
      eventType: 'feeding',
      eventDate: addDays(today, -3),
      details: 'Fed 5 dubia roaches.',
      supplements: ['calcium', 'd3'],
      createdAt: now,
    },
    {
      id: generateId(),
      reptileId: ember.id,
      eventType: 'handling',
      eventDate: addDays(today, -4),
      details: 'Handled for 15 minutes. Very active and curious.',
      createdAt: now,
    },
    {
      id: generateId(),
      reptileId: ember.id,
      eventType: 'cleaning',
      eventDate: addDays(today, -12),
      details: 'Full substrate change. Sanitized hides.',
      createdAt: now,
    },
    {
      id: generateId(),
      reptileId: nova.id,
      eventType: 'feeding',
      eventDate: addDays(today, -3),
      details: 'Fed one medium rat.',
      createdAt: now,
    },
    {
      id: generateId(),
      reptileId: nova.id,
      eventType: 'health',
      eventDate: addDays(today, -15),
      details: 'Annual checkup, all good.',
      weightGrams: 2100,
      lengthCm: 135,
      createdAt: now,
    },
  ];

  for (const event of events) {
    await db.put('careEvents', event);
  }
}

export async function clearAllData(): Promise<void> {
  const db = await getDB();
  
  // Clear all stores including Phase 2 stores
  const reptiles = await db.getAll('reptiles');
  for (const r of reptiles) {
    await db.delete('reptiles', r.id);
  }

  const events = await db.getAll('careEvents');
  for (const e of events) {
    await db.delete('careEvents', e.id);
  }

  const schedules = await db.getAll('scheduleItems');
  for (const s of schedules) {
    await db.delete('scheduleItems', s.id);
  }

  // Phase 2: Clear breeding stores
  const pairings = await db.getAll('pairings');
  for (const p of pairings) {
    await db.delete('pairings', p.id);
  }

  const clutches = await db.getAll('clutches');
  for (const c of clutches) {
    await db.delete('clutches', c.id);
  }

  const offspring = await db.getAll('offspring');
  for (const o of offspring) {
    await db.delete('offspring', o.id);
  }
}
