// Expo Demo Mode data seeding
import { getDB, generateId, getToday, addDays, getNow } from './db';
import type { Reptile, CareEvent, ScheduleItem, Pairing, Clutch } from '@/types';

export async function seedExpoDemo(): Promise<void> {
  const db = await getDB();
  const now = getNow();
  const today = getToday();

  // Keep demo loading idempotent while allowing demo data beside real data.
  const existing = await db.getAll('reptiles');
  if (existing.some(r => r.notes?.includes('[DEMO]') || r.geneticsNotes?.includes('[DEMO]'))) return;

  // Demo reptiles
  const atlas: Reptile = {
    id: generateId(),
    name: 'Atlas',
    species: 'Ball Python',
    morph: 'Banana Pastel',
    sex: 'male',
    birthDate: '2022-05-10',
    dietType: 'rodents',
    breedingStatus: 'breeder',
    notes: '[DEMO] Beautiful banana pastel male. Great feeder.',
    hets: ['clown'],
    geneticsNotes: 'Confirmed het clown from proven pairing',
    createdAt: now,
    updatedAt: now,
  };

  const luna: Reptile = {
    id: generateId(),
    name: 'Luna',
    species: 'Ball Python',
    morph: 'Piebald',
    sex: 'female',
    birthDate: '2021-11-20',
    dietType: 'rodents',
    breedingStatus: 'breeder',
    notes: '[DEMO] High-white piebald female. Excellent temperament.',
    hets: ['banana'],
    geneticsNotes: 'Visual piebald, 66% poss het banana',
    createdAt: now,
    updatedAt: now,
  };

  const spike: Reptile = {
    id: generateId(),
    name: 'Spike',
    species: 'Bearded Dragon',
    morph: 'Citrus',
    sex: 'male',
    estimatedAgeMonths: 14,
    dietType: 'mixed',
    breedingStatus: 'pet',
    notes: '[DEMO] Friendly beardie, loves greens.',
    createdAt: now,
    updatedAt: now,
  };

  await db.put('reptiles', atlas);
  await db.put('reptiles', luna);
  await db.put('reptiles', spike);

  // Demo schedules
  const schedules: ScheduleItem[] = [
    { id: generateId(), reptileId: atlas.id, taskType: 'feed', frequencyDays: 7, lastDoneDate: addDays(today, -5), nextDueDate: addDays(today, 2), autoGenerated: true },
    { id: generateId(), reptileId: atlas.id, taskType: 'clean', frequencyDays: 14, nextDueDate: addDays(today, 4), autoGenerated: true },
    { id: generateId(), reptileId: luna.id, taskType: 'feed', frequencyDays: 7, lastDoneDate: addDays(today, -3), nextDueDate: addDays(today, 4), autoGenerated: true },
    { id: generateId(), reptileId: luna.id, taskType: 'check', frequencyDays: 7, nextDueDate: today, autoGenerated: true },
    { id: generateId(), reptileId: spike.id, taskType: 'feed', frequencyDays: 2, lastDoneDate: addDays(today, -2), nextDueDate: today, autoGenerated: true },
    { id: generateId(), reptileId: spike.id, taskType: 'clean', frequencyDays: 7, nextDueDate: addDays(today, 3), autoGenerated: true },
  ];

  for (const s of schedules) await db.put('scheduleItems', s);

  // Demo events
  const events: CareEvent[] = [
    { id: generateId(), reptileId: atlas.id, eventType: 'feeding', eventDate: addDays(today, -5), details: '[DEMO] Fed medium rat', supplements: ['calcium'], createdAt: now },
    { id: generateId(), reptileId: atlas.id, eventType: 'health', eventDate: addDays(today, -14), details: '[DEMO] Weight check', weightGrams: 1950, createdAt: now },
    { id: generateId(), reptileId: atlas.id, eventType: 'shedding', eventDate: addDays(today, -10), details: '[DEMO] Complete one-piece shed', createdAt: now },
    { id: generateId(), reptileId: luna.id, eventType: 'feeding', eventDate: addDays(today, -3), details: '[DEMO] Fed medium rat', createdAt: now },
    { id: generateId(), reptileId: luna.id, eventType: 'health', eventDate: addDays(today, -7), details: '[DEMO] Routine check', weightGrams: 2200, createdAt: now },
    { id: generateId(), reptileId: spike.id, eventType: 'feeding', eventDate: addDays(today, -2), details: '[DEMO] Dubia roaches + greens', supplements: ['calcium', 'd3'], createdAt: now },
    { id: generateId(), reptileId: spike.id, eventType: 'handling', eventDate: addDays(today, -1), details: '[DEMO] 20 min handling session', createdAt: now },
  ];

  for (const e of events) await db.put('careEvents', e);

  // Demo pairing
  const pairing: Pairing = {
    id: generateId(),
    parentAId: atlas.id,
    parentBId: luna.id,
    startDate: addDays(today, -45),
    status: 'active',
    notes: '[DEMO] Banana Pastel x Piebald project',
    createdAt: now,
  };
  await db.put('pairings', pairing);

  // Demo clutch
  const clutch: Clutch = {
    id: generateId(),
    pairingId: pairing.id,
    laidDate: addDays(today, -20),
    eggCount: 7,
    expectedHatchDate: addDays(today, 35),
    createdAt: now,
  };
  await db.put('clutches', clutch);
}

/** Remove only demo-tagged data (items with [DEMO] in notes/details) */
export async function clearDemoData(): Promise<void> {
  const db = await getDB();

  // Find demo reptiles
  const reptiles = await db.getAll('reptiles');
  const demoReptileIds = new Set<string>();
  for (const r of reptiles) {
    if (r.notes?.includes('[DEMO]') || r.geneticsNotes?.includes('[DEMO]')) {
      demoReptileIds.add(r.id);
      await db.delete('reptiles', r.id);
    }
  }

  // Remove events tagged with [DEMO] or belonging to demo reptiles
  const events = await db.getAll('careEvents');
  for (const e of events) {
    if (e.details?.includes('[DEMO]') || demoReptileIds.has(e.reptileId)) {
      await db.delete('careEvents', e.id);
    }
  }

  // Remove schedules belonging to demo reptiles
  const schedules = await db.getAll('scheduleItems');
  for (const s of schedules) {
    if (demoReptileIds.has(s.reptileId)) {
      await db.delete('scheduleItems', s.id);
    }
  }

  // Remove pairings involving demo reptiles
  const pairings = await db.getAll('pairings');
  const demoPairingIds = new Set<string>();
  for (const p of pairings) {
    if (demoReptileIds.has(p.parentAId) || demoReptileIds.has(p.parentBId) || p.notes?.includes('[DEMO]')) {
      demoPairingIds.add(p.id);
      await db.delete('pairings', p.id);
    }
  }

  // Remove clutches from demo pairings
  const clutches = await db.getAll('clutches');
  for (const c of clutches) {
    if (demoPairingIds.has(c.pairingId)) {
      await db.delete('clutches', c.id);
    }
  }
}
