// Reptile CRUD operations
import { getDB, generateId, getNow, getToday, addDays } from './db';
import { revokePublicSharesForAnimal } from '@/lib/share/revokePublicShares';
import type { Reptile, ReptileFormData, ScheduleItem, DietType } from '@/types';

// Get feeding frequency (days) based on diet type. Legacy + expanded for reptiles/amphibians.
function getFeedingFrequency(dietType: DietType): number {
  switch (dietType) {
    case 'insects': return 2;
    case 'rodents': return 7;
    case 'mixed': return 3;
    case 'fish': return 3;
    case 'herbivore': return 1;
    case 'omnivore': return 3;
    case 'pellets': return 2;
    default: return 5;
  }
}

// Generate default schedule for a new reptile
function generateDefaultSchedule(reptileId: string, dietType: DietType): ScheduleItem[] {
  const today = getToday();
  const feedFreq = getFeedingFrequency(dietType);

  return [
    {
      id: generateId(),
      reptileId,
      taskType: 'feed',
      frequencyDays: feedFreq,
      nextDueDate: addDays(today, feedFreq),
      autoGenerated: true,
    },
    {
      id: generateId(),
      reptileId,
      taskType: 'clean',
      frequencyDays: 14,
      nextDueDate: addDays(today, 14),
      autoGenerated: true,
    },
    {
      id: generateId(),
      reptileId,
      taskType: 'check',
      frequencyDays: 7,
      nextDueDate: addDays(today, 7),
      autoGenerated: true,
    },
  ];
}

// Create a new reptile with auto-generated schedule
export async function createReptile(data: ReptileFormData): Promise<Reptile> {
  const db = await getDB();
  const now = getNow();
  
  const reptile: Reptile = {
    id: generateId(),
    name: data.name,
    species: data.species,
    commonName: data.commonName,
    scientificName: data.scientificName,
    animalClass: data.animalClass,
    animalCategory: data.animalCategory,
    speciesGroup: data.speciesGroup,
    morph: data.morph,
    sex: data.sex,
    birthDate: data.birthDate,
    estimatedAgeMonths: data.estimatedAgeMonths,
    acquisitionDate: data.acquisitionDate,
    dietType: data.dietType,
    breedingStatus: data.breedingStatus || 'pet',
    notes: data.notes,
    habitatType: data.habitatType,
    humidityPreference: data.humidityPreference,
    temperaturePreference: data.temperaturePreference,
    uvbRequirement: data.uvbRequirement,
    waterRequirement: data.waterRequirement,
    handlingProfile: data.handlingProfile,
    isVenomous: data.isVenomous,
    isDangerous: data.isDangerous,
    isAmphibian: data.isAmphibian,
    geneticsNotes: data.geneticsNotes,
    hets: data.hets,
    genes: data.genes,
    photoUrl: data.photoUrl?.trim() || undefined,
    createdAt: now,
    updatedAt: now,
  };

  // Save reptile
  await db.put('reptiles', reptile);

  // Generate and save default schedule
  const scheduleItems = generateDefaultSchedule(reptile.id, reptile.dietType);
  const tx = db.transaction('scheduleItems', 'readwrite');
  for (const item of scheduleItems) {
    await tx.store.put(item);
  }
  await tx.done;

  return reptile;
}

// Get all reptiles
export async function getAllReptiles(): Promise<Reptile[]> {
  const db = await getDB();
  return db.getAll('reptiles');
}

// Get a single reptile by ID
export async function getReptileById(id: string): Promise<Reptile | undefined> {
  const db = await getDB();
  return db.get('reptiles', id);
}

// Update a reptile
export async function updateReptile(id: string, data: Partial<ReptileFormData>): Promise<Reptile | undefined> {
  const db = await getDB();
  const existing = await db.get('reptiles', id);
  
  if (!existing) return undefined;

  const updated: Reptile = {
    ...existing,
    ...data,
    updatedAt: getNow(),
  };

  await db.put('reptiles', updated);
  return updated;
}

// Delete a reptile and all related data
export async function deleteReptile(id: string): Promise<void> {
  const db = await getDB();

  try {
    await revokePublicSharesForAnimal(id);
  } catch (error) {
    console.warn('Failed to revoke public shares for deleted animal:', error);
  }

  // Delete breeding records that depend on pairings involving this animal.
  // This mirrors deletePairing/deleteClutch behavior without importing those modules
  // here, so deleting an animal cannot leave orphaned clutches or offspring.
  const pairings = await db.getAll('pairings');
  const dependentPairings = pairings.filter((pairing) => pairing.parentAId === id || pairing.parentBId === id);
  for (const pairing of dependentPairings) {
    const clutches = await db.getAllFromIndex('clutches', 'by-pairing', pairing.id);
    for (const clutch of clutches) {
      const offspring = await db.getAllFromIndex('offspring', 'by-clutch', clutch.id);
      const offspringTx = db.transaction('offspring', 'readwrite');
      for (const item of offspring) {
        await offspringTx.store.delete(item.id);
      }
      await offspringTx.done;
      await db.delete('clutches', clutch.id);
    }
    await db.delete('pairings', pairing.id);
  }

  // Delete reptile
  await db.delete('reptiles', id);

  // Delete all care events for this reptile
  const events = await db.getAllFromIndex('careEvents', 'by-reptile', id);
  const eventTx = db.transaction('careEvents', 'readwrite');
  for (const event of events) {
    await eventTx.store.delete(event.id);
  }
  await eventTx.done;

  // Delete all schedule items for this reptile
  const schedules = await db.getAllFromIndex('scheduleItems', 'by-reptile', id);
  const scheduleTx = db.transaction('scheduleItems', 'readwrite');
  for (const schedule of schedules) {
    await scheduleTx.store.delete(schedule.id);
  }
  await scheduleTx.done;
}

// Search reptiles by name or species
export async function searchReptiles(query: string): Promise<Reptile[]> {
  const db = await getDB();
  const all = await db.getAll('reptiles');
  const lowerQuery = query.toLowerCase();
  
  return all.filter(r => 
    r.name.toLowerCase().includes(lowerQuery) ||
    r.species.toLowerCase().includes(lowerQuery)
  );
}
