// Reptile CRUD operations
import { getDB, generateId, getNow, getToday, addDays } from './db';
import { revokePublicSharesForAnimal } from '@/lib/share/revokePublicShares';
import { deleteCurrentUserCloudReptile, upsertCurrentUserCloudReptile } from '@/lib/reptiles/cloudSync';
import { ensureInlinePhotoBackedUp, resolveDisplayPhotoForReptile } from '@/lib/reptiles/photoStorage';
import { resolveAnimalGroup } from '@/lib/animals/taxonomy';
import { toast } from 'sonner';
import type { Reptile, ReptileFormData, ScheduleItem, DietType } from '@/types';

// Get feeding frequency (days) based on diet type. Legacy + expanded for reptiles/amphibians.
function getFeedingFrequency(dietType: DietType): number {
  switch (dietType) {
    case 'insects': return 2;
    case 'rodents': return 7;
    case 'mixed': return 3;
    case 'fish': return 3;
    case 'herbivore': return 1;
    case 'omnivore': return 3;
    case 'pellets': return 2;
    default: return 5;
  }
}

// Generate default schedule for a new reptile
function generateDefaultSchedule(reptileId: string, dietType: DietType): ScheduleItem[] {
  const today = getToday();
  const feedFreq = getFeedingFrequency(dietType);

  const ts = getNow();
  return [
    {
      id: generateId(),
      reptileId,
      taskType: 'feed',
      frequencyDays: feedFreq,
      nextDueDate: addDays(today, feedFreq),
      autoGenerated: true,
      updatedAt: ts,
    },
    {
      id: generateId(),
      reptileId,
      taskType: 'clean',
      frequencyDays: 14,
      nextDueDate: addDays(today, 14),
      autoGenerated: true,
      updatedAt: ts,
    },
    {
      id: generateId(),
      reptileId,
      taskType: 'check',
      frequencyDays: 7,
      nextDueDate: addDays(today, 7),
      autoGenerated: true,
      updatedAt: ts,
    },
  ];
}

function syncReptileUpsertInBackground(reptile: Reptile): void {
  void upsertCurrentUserCloudReptile(reptile).catch((error) => {
    console.warn('Cloud reptile upsert skipped:', error);
  });
}

function backupPhotoToStorageInBackground(reptile: Reptile, opts?: { notifyOnError?: boolean }): void {
  void (async () => {
    const result = await ensureInlinePhotoBackedUp({ reptile });
    if (result.uploaded) {
      const db = await getDB();
      const existing = await db.get('reptiles', reptile.id);
      if (!existing) return;
      const updated: Reptile = {
        ...existing,
        photoPath: result.reptile.photoPath,
      };
      await db.put('reptiles', updated);
      syncReptileUpsertInBackground(updated);
      return;
    }
    if (result.error && opts?.notifyOnError) {
      toast.info('Photo saved on this device. Cloud photo backup was not completed yet.');
    }
  })().catch((error) => {
    console.warn('Cloud photo backup skipped:', error);
    if (opts?.notifyOnError) {
      toast.info('Photo saved on this device. Cloud photo backup was not completed yet.');
    }
  });
}

function syncReptileDeleteInBackground(reptileId: string): void {
  void deleteCurrentUserCloudReptile(reptileId).catch((error) => {
    console.warn('Cloud reptile delete skipped:', error);
  });
}

function compareReptilesDisplayOrder(a: Reptile, b: Reptile): number {
  const ao = a.sortOrder;
  const bo = b.sortOrder;
  if (typeof ao === 'number' && typeof bo === 'number' && ao !== bo) return ao - bo;
  if (typeof ao === 'number' && typeof bo !== 'number') return -1;
  if (typeof ao !== 'number' && typeof bo === 'number') return 1;
  const byCreated = a.createdAt.localeCompare(b.createdAt);
  if (byCreated !== 0) return byCreated;
  return a.name.localeCompare(b.name, undefined, { sensitivity: 'base' });
}

async function refreshDisplayPhotosFromStorage(reptiles: Reptile[]): Promise<Reptile[]> {
  const db = await getDB();
  const refreshed = await Promise.all(reptiles.map(async (reptile) => resolveDisplayPhotoForReptile(reptile)));
  const changed = refreshed.filter((r) => r.refreshed).map((r) => r.reptile);
  for (const reptile of changed) {
    await db.put('reptiles', reptile);
  }
  return refreshed.map((r) => r.reptile);
}

/** Assigns contiguous `sortOrder` when legacy rows are missing it (one-time per device). */
async function ensureReptilesHaveSortOrderAssigned(db: Awaited<ReturnType<typeof getDB>>): Promise<void> {
  const all = await db.getAll('reptiles');
  if (all.length === 0) return;
  if (all.every((r) => typeof r.sortOrder === 'number')) return;

  const sorted = [...all].sort(compareReptilesDisplayOrder);
  const now = getNow();
  const tx = db.transaction('reptiles', 'readwrite');
  for (let i = 0; i < sorted.length; i++) {
    const r = sorted[i];
    await tx.store.put({ ...r, sortOrder: i, updatedAt: now });
    syncReptileUpsertInBackground({ ...r, sortOrder: i, updatedAt: now });
  }
  await tx.done;
}

// Create a new reptile with auto-generated schedule
export async function createReptile(data: ReptileFormData): Promise<Reptile> {
  const db = await getDB();
  const now = getNow();
  const existing = await db.getAll('reptiles');
  const maxOrder = existing.reduce(
    (m, r) => Math.max(m, typeof r.sortOrder === 'number' ? r.sortOrder : -1),
    -1,
  );

  const reptile: Reptile = {
    id: generateId(),
    name: data.name,
    species: data.species,
    commonName: data.commonName,
    scientificName: data.scientificName,
    animalGroup: data.animalGroup ?? resolveAnimalGroup(data),
    animalClass: data.animalClass,
    animalCategory: data.animalCategory,
    speciesGroup: data.speciesGroup,
    morph: data.morph,
    sex: data.sex,
    birthDate: data.birthDate,
    estimatedAgeMonths: data.estimatedAgeMonths,
    acquisitionDate: data.acquisitionDate?.trim() ? data.acquisitionDate : undefined,
    dietType: data.dietType,
    breedingStatus: data.breedingStatus || 'pet',
    notes: data.notes,
    habitatType: data.habitatType,
    humidityPreference: data.humidityPreference,
    temperaturePreference: data.temperaturePreference,
    uvbRequirement: data.uvbRequirement,
    waterRequirement: data.waterRequirement,
    handlingProfile: data.handlingProfile,
    isVenomous: data.isVenomous,
    isDangerous: data.isDangerous,
    isAmphibian: data.isAmphibian,
    geneticsNotes: data.geneticsNotes,
    hets: data.hets,
    genes: data.genes,
    photoUrl: data.photoUrl?.trim() || undefined,
    photoPath: data.photoPath?.trim() || undefined,
    sortOrder: maxOrder + 1,
    createdAt: now,
    updatedAt: now,
  };

  // Save reptile
  await db.put('reptiles', reptile);

  // Generate and save default schedule
  const scheduleItems = generateDefaultSchedule(reptile.id, reptile.dietType);
  const tx = db.transaction('scheduleItems', 'readwrite');
  for (const item of scheduleItems) {
    await tx.store.put(item);
  }
  await tx.done;

  syncReptileUpsertInBackground(reptile);
  backupPhotoToStorageInBackground(reptile, { notifyOnError: true });

  return reptile;
}

// Get all reptiles
export async function getAllReptiles(): Promise<Reptile[]> {
  const db = await getDB();
  await ensureReptilesHaveSortOrderAssigned(db);
  const all = await db.getAll('reptiles');
  const withFreshPhotos = await refreshDisplayPhotosFromStorage(all);
  return [...withFreshPhotos].sort(compareReptilesDisplayOrder);
}

/** Persist My Animals order after drag-and-drop (`orderedIds` is the full list, index 0 = top). */
export async function persistReptilesDisplayOrder(orderedIds: string[]): Promise<void> {
  const db = await getDB();
  const now = getNow();
  for (let i = 0; i < orderedIds.length; i++) {
    const id = orderedIds[i];
    const r = await db.get('reptiles', id);
    if (!r) continue;
    const next: Reptile = { ...r, sortOrder: i, updatedAt: now };
    await db.put('reptiles', next);
    syncReptileUpsertInBackground(next);
  }
}

// Get a single reptile by ID
export async function getReptileById(id: string): Promise<Reptile | undefined> {
  const db = await getDB();
  const reptile = await db.get('reptiles', id);
  if (!reptile) return undefined;
  const resolved = await resolveDisplayPhotoForReptile(reptile);
  if (resolved.refreshed) {
    await db.put('reptiles', resolved.reptile);
  }
  return resolved.reptile;
}

// Update a reptile
export async function updateReptile(id: string, data: Partial<ReptileFormData>): Promise<Reptile | undefined> {
  const db = await getDB();
  const existing = await db.get('reptiles', id);
  
  if (!existing) return undefined;

  const updated: Reptile = {
    ...existing,
    ...data,
    updatedAt: getNow(),
  };
  if ('acquisitionDate' in data) {
    updated.acquisitionDate = data.acquisitionDate?.trim() ? data.acquisitionDate : undefined;
  }

  await db.put('reptiles', updated);
  syncReptileUpsertInBackground(updated);
  backupPhotoToStorageInBackground(updated, { notifyOnError: true });
  return updated;
}

// Delete a reptile and all related data
export async function deleteReptile(id: string): Promise<void> {
  const db = await getDB();

  try {
    await revokePublicSharesForAnimal(id);
  } catch (error) {
    console.warn('Failed to revoke public shares for deleted animal:', error);
  }

  // Delete breeding records that depend on pairings involving this animal.
  // This mirrors deletePairing/deleteClutch behavior without importing those modules
  // here, so deleting an animal cannot leave orphaned clutches or offspring.
  const pairings = await db.getAll('pairings');
  const dependentPairings = pairings.filter((pairing) => pairing.parentAId === id || pairing.parentBId === id);
  for (const pairing of dependentPairings) {
    const clutches = await db.getAllFromIndex('clutches', 'by-pairing', pairing.id);
    for (const clutch of clutches) {
      const offspring = await db.getAllFromIndex('offspring', 'by-clutch', clutch.id);
      const offspringTx = db.transaction('offspring', 'readwrite');
      for (const item of offspring) {
        await offspringTx.store.delete(item.id);
      }
      await offspringTx.done;
      await db.delete('clutches', clutch.id);
    }
    await db.delete('pairings', pairing.id);
  }

  // Delete reptile
  await db.delete('reptiles', id);
  syncReptileDeleteInBackground(id);

  // Delete all care events for this reptile
  const events = await db.getAllFromIndex('careEvents', 'by-reptile', id);
  const eventTx = db.transaction('careEvents', 'readwrite');
  for (const event of events) {
    await eventTx.store.delete(event.id);
  }
  await eventTx.done;

  // Delete all schedule items for this reptile
  const schedules = await db.getAllFromIndex('scheduleItems', 'by-reptile', id);
  const scheduleTx = db.transaction('scheduleItems', 'readwrite');
  for (const schedule of schedules) {
    await scheduleTx.store.delete(schedule.id);
  }
  await scheduleTx.done;
}

// Search reptiles by name or species
export async function searchReptiles(query: string): Promise<Reptile[]> {
  const db = await getDB();
  const all = await db.getAll('reptiles');
  const lowerQuery = query.toLowerCase();
  
  return all.filter(r => 
    r.name.toLowerCase().includes(lowerQuery) ||
    r.species.toLowerCase().includes(lowerQuery)
  );
}
