// ScheduleItem CRUD operations
import { getDB, getToday, addDays, getNow, isOverdue, isDueToday, isWithinDays } from './db';
import { parseLocalDateKey } from '@/lib/date/localDateKey';
import type { ScheduleItem, ScheduleMode, TaskType, CareEvent, EventType } from '@/types';
import { createCareEvent } from './events';

/** Default repeating care schedules (excludes manual / assistant-added rows). */
export function isRecurringCareTask(item: ScheduleItem): boolean {
  return isStrictRecurringCareTask(item);
}

export function getScheduleMode(item: ScheduleItem): ScheduleMode {
  if (item.scheduleMode === 'weekdays' || item.scheduleMode === 'flexible') return item.scheduleMode;
  return 'interval';
}

export function isFlexibleScheduleItem(item: ScheduleItem): boolean {
  return getScheduleMode(item) === 'flexible';
}

export function isStrictRecurringCareTask(item: ScheduleItem): boolean {
  return item.autoGenerated === true && item.frequencyDays > 0 && !isFlexibleScheduleItem(item);
}

export function normalizeWeekdays(days?: number[]): number[] {
  if (!days?.length) return [];
  const normalized = days
    .map((d) => Number(d))
    .filter((d) => Number.isInteger(d) && d >= 0 && d <= 6);
  return [...new Set(normalized)].sort((a, b) => a - b);
}

export function computeNextWeekdayDate(weekdays: number[] | undefined, anchorDateKey: string): string {
  const selected = new Set(normalizeWeekdays(weekdays));
  if (selected.size === 0) return anchorDateKey;
  const anchor = parseLocalDateKey(anchorDateKey);
  if (Number.isNaN(anchor.getTime())) return anchorDateKey;

  for (let i = 1; i <= 7; i++) {
    const next = new Date(anchor);
    next.setDate(next.getDate() + i);
    if (selected.has(next.getDay())) {
      return `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}-${String(next.getDate()).padStart(2, '0')}`;
    }
  }
  return anchorDateKey;
}

export function computeNextDueDate(item: ScheduleItem, anchorDateKey: string): string {
  const safeFrequency = Math.max(1, item.frequencyDays || 1);
  const mode = getScheduleMode(item);
  if (mode === 'weekdays') {
    const nextWeekday = computeNextWeekdayDate(item.weekdays, anchorDateKey);
    if (nextWeekday !== anchorDateKey) return nextWeekday;
  }
  return addDays(anchorDateKey, safeFrequency);
}

/**
 * From the current stored due date, step forward by `frequencyDays` until due date is not before `todayStr`.
 * Does not write to storage.
 */
export function computeNextDueAfterSkippingOverdueSlots(item: ScheduleItem, todayStr: string): string {
  if (getScheduleMode(item) === 'weekdays') {
    let next = item.nextDueDate;
    while (next < todayStr) {
      next = computeNextWeekdayDate(item.weekdays, next);
      if (next === item.nextDueDate) break;
    }
    return next;
  }
  const freq = Math.max(1, item.frequencyDays || 1);
  let next = item.nextDueDate;
  while (next < todayStr) {
    next = addDays(next, freq);
  }
  return next;
}

/**
 * Overdue auto-generated tasks only: set next due to one full interval after today.
 * Does not change `lastDoneDate` and does not create journal events.
 */
export async function advanceOverdueRecurringTasksStartFresh(scheduleItemIds: string[]): Promise<string[]> {
  const db = await getDB();
  const today = getToday();
  const updated: string[] = [];
  for (const id of scheduleItemIds) {
    const item = await db.get('scheduleItems', id);
    if (!item || !isStrictRecurringCareTask(item)) continue;
    if (!isOverdue(item.nextDueDate)) continue;
    const nextDueDate = computeNextDueDate(item, today);
    await db.put('scheduleItems', { ...item, nextDueDate, updatedAt: getNow() });
    updated.push(id);
  }
  return updated;
}

/**
 * Overdue auto-generated tasks only: roll `nextDueDate` forward by intervals until caught up to today or later.
 * Does not change `lastDoneDate` and does not create journal events.
 */
export async function advanceOverdueRecurringTasksSkipOverdue(scheduleItemIds: string[]): Promise<string[]> {
  const db = await getDB();
  const today = getToday();
  const updated: string[] = [];
  for (const id of scheduleItemIds) {
    const item = await db.get('scheduleItems', id);
    if (!item || !isStrictRecurringCareTask(item)) continue;
    if (!isOverdue(item.nextDueDate)) continue;
    const nextDueDate = computeNextDueAfterSkippingOverdueSlots(item, today);
    if (nextDueDate === item.nextDueDate) continue;
    await db.put('scheduleItems', { ...item, nextDueDate, updatedAt: getNow() });
    updated.push(id);
  }
  return updated;
}

// Get all schedule items
export async function getAllScheduleItems(): Promise<ScheduleItem[]> {
  const db = await getDB();
  return db.getAll('scheduleItems');
}

// Get schedule items for a specific reptile
export async function getScheduleByReptile(reptileId: string): Promise<ScheduleItem[]> {
  const db = await getDB();
  return db.getAllFromIndex('scheduleItems', 'by-reptile', reptileId);
}

// Get tasks due today
export async function getTasksDueToday(): Promise<ScheduleItem[]> {
  const all = await getAllScheduleItems();
  return all.filter(item => isDueToday(item.nextDueDate));
}

// Get overdue tasks
export async function getOverdueTasks(): Promise<ScheduleItem[]> {
  const all = await getAllScheduleItems();
  return all.filter(item => isStrictRecurringCareTask(item) && isOverdue(item.nextDueDate));
}

// Get tasks due within next N days (including today)
export async function getUpcomingTasks(days: number): Promise<ScheduleItem[]> {
  const all = await getAllScheduleItems();
  return all
    .filter(item => isWithinDays(item.nextDueDate, days) || isOverdue(item.nextDueDate))
    .sort((a, b) => a.nextDueDate.localeCompare(b.nextDueDate));
}

// Map task type to event type
function taskTypeToEventType(taskType: TaskType): EventType {
  switch (taskType) {
    case 'feed': return 'feeding';
    case 'clean': return 'cleaning';
    case 'check': return 'note';
  }
}

// Get default details for auto-generated events
function getDefaultDetails(taskType: TaskType): string {
  switch (taskType) {
    case 'feed': return 'Feeding completed';
    case 'clean': return 'Enclosure cleaned';
    case 'check': return 'Routine check completed';
  }
}

// Mark a task as done - updates schedule and creates care event
export async function markTaskDone(
  scheduleItemId: string, 
  details?: string
): Promise<{ scheduleItem: ScheduleItem; careEvent: CareEvent }> {
  const db = await getDB();
  const item = await db.get('scheduleItems', scheduleItemId);
  
  if (!item) {
    throw new Error('Schedule item not found');
  }

  const today = getToday();

  // Update schedule item
  const updatedItem: ScheduleItem = {
    ...item,
    lastDoneDate: today,
    nextDueDate: computeNextDueDate(item, today),
    updatedAt: getNow(),
  };

  await db.put('scheduleItems', updatedItem);

  // Create care event
  const careEvent = await createCareEvent({
    reptileId: item.reptileId,
    eventType: taskTypeToEventType(item.taskType),
    eventDate: today,
    details: details || getDefaultDetails(item.taskType),
  });

  return { scheduleItem: updatedItem, careEvent };
}

/**
 * Mark each overdue recurring task as completed today (same as single `markTaskDone`), in series.
 * Returns ids touched for cloud push.
 */
export async function markOverdueRecurringTasksDoneBulk(scheduleItemIds: string[]): Promise<{
  scheduleItemIds: string[];
}> {
  const db = await getDB();
  const unique = [...new Set(scheduleItemIds)].filter(Boolean);
  const scheduleItemIdsOut: string[] = [];
  for (const id of unique) {
    const item = await db.get('scheduleItems', id);
    if (!item || !isStrictRecurringCareTask(item)) continue;
    if (!isOverdue(item.nextDueDate)) continue;
    const { scheduleItem } = await markTaskDone(id);
    scheduleItemIdsOut.push(scheduleItem.id);
  }
  return { scheduleItemIds: scheduleItemIdsOut };
}

// Update schedule item frequency
export async function updateScheduleFrequency(
  scheduleItemId: string, 
  frequencyDays: number
): Promise<ScheduleItem | undefined> {
  const db = await getDB();
  const item = await db.get('scheduleItems', scheduleItemId);
  
  if (!item) return undefined;

  const today = getToday();
  const updated: ScheduleItem = {
    ...item,
    frequencyDays: Math.max(1, frequencyDays || 1),
    // Recalculate next due date from today
    nextDueDate: computeNextDueDate({ ...item, frequencyDays: Math.max(1, frequencyDays || 1) }, today),
    scheduleMode: item.scheduleMode,
    weekdays: normalizeWeekdays(item.weekdays),
    updatedAt: getNow(),
  };

  await db.put('scheduleItems', updated);
  return updated;
}

export async function updateScheduleRule(
  scheduleItemId: string,
  updates: {
    frequencyDays?: number;
    scheduleMode?: ScheduleMode;
    weekdays?: number[];
  },
): Promise<ScheduleItem | undefined> {
  const db = await getDB();
  const item = await db.get('scheduleItems', scheduleItemId);
  if (!item) return undefined;

  const today = getToday();
  const nextMode = updates.scheduleMode ?? item.scheduleMode ?? 'interval';
  const nextFrequency = Math.max(1, updates.frequencyDays ?? item.frequencyDays ?? 1);
  const nextWeekdays = nextMode === 'weekdays' ? normalizeWeekdays(updates.weekdays ?? item.weekdays) : undefined;

  const candidate: ScheduleItem = {
    ...item,
    frequencyDays: nextFrequency,
    scheduleMode: nextMode,
    weekdays: nextWeekdays,
  };

  const updated: ScheduleItem = {
    ...candidate,
    nextDueDate: computeNextDueDate(candidate, today),
    updatedAt: getNow(),
  };

  await db.put('scheduleItems', updated);
  return updated;
}

/** Backfill `updatedAt` for legacy IndexedDB rows (required for cloud merge). */
export async function ensureScheduleItemsHaveTimestamps(): Promise<number> {
  const db = await getDB();
  const items = await db.getAll('scheduleItems');
  const ts = getNow();
  let changed = 0;
  for (const item of items) {
    if (item.updatedAt) continue;
    await db.put('scheduleItems', { ...item, updatedAt: ts });
    changed++;
  }
  return changed;
}

/** Same as `ensureScheduleItemsHaveTimestamps` but only for the given ids (e.g. narrow cloud upsert). */
export async function ensureScheduleItemsHaveTimestampsForIds(scheduleItemIds: string[]): Promise<number> {
  const unique = [...new Set(scheduleItemIds)].filter(Boolean);
  if (unique.length === 0) return 0;

  const db = await getDB();
  const ts = getNow();
  let changed = 0;
  for (const id of unique) {
    const item = await db.get('scheduleItems', id);
    if (!item || item.updatedAt) continue;
    await db.put('scheduleItems', { ...item, updatedAt: ts });
    changed++;
  }
  return changed;
}

// Delete a schedule item
export async function deleteScheduleItem(id: string): Promise<void> {
  const db = await getDB();
  await db.delete('scheduleItems', id);
}

// Get next feeding date for a reptile
export async function getNextFeedingDate(reptileId: string): Promise<string | undefined> {
  const schedules = await getScheduleByReptile(reptileId);
  const feedSchedule = schedules.find(s => s.taskType === 'feed');
  return feedSchedule?.nextDueDate;
}

/**
 * When logging feeding/cleaning for *today*, align an existing matching schedule row
 * (never creates schedules). Conservative: exact calendar match to local today only.
 */
export async function reconcileScheduleAfterManualCareEvent(
  reptileId: string,
  eventType: EventType,
  eventDateKey: string,
): Promise<string | undefined> {
  let taskType: TaskType | null = null;
  if (eventType === 'feeding') taskType = 'feed';
  else if (eventType === 'cleaning') taskType = 'clean';

  if (!taskType) return undefined;

  const today = getToday();
  if (eventDateKey !== today) return undefined;

  const db = await getDB();
  const items = await db.getAllFromIndex('scheduleItems', 'by-reptile', reptileId);
  const match = items.find((i) => i.taskType === taskType);
  if (!match) return undefined;

  const updated: ScheduleItem = {
    ...match,
    lastDoneDate: eventDateKey,
    nextDueDate: computeNextDueDate(match, eventDateKey),
    updatedAt: getNow(),
  };
  await db.put('scheduleItems', updated);
  return match.id;
}
