// Reptilita Data Model Types

import type { GeneticGene } from './genetics';
import type {
  AnimalClass,
  AnimalCategory,
  HabitatType,
  HumidityPreference,
  TemperaturePreference,
  UVBRequirement,
  WaterRequirement,
  HandlingProfile,
} from '@/lib/animals/taxonomy';

export type Sex = "unknown" | "male" | "female";
export type DietType = "insects" | "rodents" | "fish" | "herbivore" | "omnivore" | "pellets" | "mixed";
export type EventType = "feeding" | "cleaning" | "shedding" | "health" | "handling" | "note";
export type TaskType = "feed" | "clean" | "check";
export type BreedingStatus = "pet" | "breeder" | "hold";
export type Supplement = "calcium" | "d3" | "multivitamin";
export type PairingStatus = "planned" | "active" | "completed" | "cancelled";

export interface Reptile {
  id: string;
  name: string;
  species: string;
  commonName?: string;
  scientificName?: string;
  animalClass?: AnimalClass;
  animalCategory?: AnimalCategory;
  speciesGroup?: string;
  morph?: string;
  sex: Sex;
  birthDate?: string; // ISO date
  estimatedAgeMonths?: number;
  acquisitionDate?: string; // ISO date
  dietType: DietType;
  breedingStatus: BreedingStatus;
  notes?: string;
  habitatType?: HabitatType;
  humidityPreference?: HumidityPreference;
  temperaturePreference?: TemperaturePreference;
  uvbRequirement?: UVBRequirement;
  waterRequirement?: WaterRequirement;
  handlingProfile?: HandlingProfile;
  isVenomous?: boolean;
  isDangerous?: boolean;
  isAmphibian?: boolean;
  // Phase 2: Genetics fields (basic)
  geneticsNotes?: string;
  hets?: string[]; // List of recessive het traits (legacy/basic)
  // Phase 3: Advanced genetics
  genes?: GeneticGene[]; // Structured gene data
  photoUrl?: string;
  createdAt: string; // ISO datetime
  updatedAt: string; // ISO datetime
}

export interface CareEvent {
  id: string;
  reptileId: string;
  eventType: EventType;
  eventDate: string; // ISO date
  details?: string;
  photoDataUrl?: string;
  // Phase 1.5: Health metrics (optional, for health events)
  weightGrams?: number;
  lengthCm?: number;
  // Phase 1.5: Supplement tracking (optional, for feeding events)
  supplements?: Supplement[];
  createdAt: string; // ISO datetime
}

export interface ScheduleItem {
  id: string;
  reptileId: string;
  taskType: TaskType;
  frequencyDays: number;
  lastDoneDate?: string; // ISO date
  nextDueDate: string; // ISO date
  autoGenerated: boolean;
}

// Phase 2: Breeding entities
export interface Pairing {
  id: string;
  parentAId: string; // reptileId
  parentBId: string; // reptileId
  startDate: string; // ISO date
  status: PairingStatus;
  notes?: string;
  createdAt: string; // ISO datetime
}

export interface Clutch {
  id: string;
  pairingId: string;
  laidDate: string; // ISO date
  eggCount: number;
  incubatorNotes?: string;
  expectedHatchDate?: string; // ISO date
  hatchCount?: number;
  createdAt: string; // ISO datetime
}

export interface Offspring {
  id: string;
  clutchId: string;
  name?: string;
  sex: Sex;
  morph?: string;
  hets?: string[];
  notes?: string;
  createdAt: string; // ISO datetime
}

// Helper types for UI
export interface TaskWithReptile extends ScheduleItem {
  reptile: Reptile;
  isOverdue: boolean;
  isDueToday: boolean;
}

export interface EventWithReptile extends CareEvent {
  reptile: Reptile;
}

export interface PairingWithReptiles extends Pairing {
  parentA: Reptile;
  parentB: Reptile;
}

// Form types
export interface ReptileFormData {
  name: string;
  species: string;
  commonName?: string;
  scientificName?: string;
  animalClass?: AnimalClass;
  animalCategory?: AnimalCategory;
  speciesGroup?: string;
  morph?: string;
  sex: Sex;
  birthDate?: string;
  estimatedAgeMonths?: number;
  acquisitionDate?: string;
  dietType: DietType;
  breedingStatus: BreedingStatus;
  notes?: string;
  habitatType?: HabitatType;
  humidityPreference?: HumidityPreference;
  temperaturePreference?: TemperaturePreference;
  uvbRequirement?: UVBRequirement;
  waterRequirement?: WaterRequirement;
  handlingProfile?: HandlingProfile;
  isVenomous?: boolean;
  isDangerous?: boolean;
  isAmphibian?: boolean;
  geneticsNotes?: string;
  hets?: string[];
  genes?: GeneticGene[];
  photoUrl?: string;
}

export interface CareEventFormData {
  reptileId: string;
  eventType: EventType;
  eventDate: string;
  details?: string;
  photoDataUrl?: string;
  weightGrams?: number;
  lengthCm?: number;
  supplements?: Supplement[];
}

export interface PairingFormData {
  parentAId: string;
  parentBId: string;
  startDate: string;
  status: PairingStatus;
  notes?: string;
}

export interface ClutchFormData {
  pairingId: string;
  laidDate: string;
  eggCount: number;
  incubatorNotes?: string;
  expectedHatchDate?: string;
}

export interface OffspringFormData {
  clutchId: string;
  name?: string;
  sex: Sex;
  morph?: string;
  hets?: string[];
  notes?: string;
}

// Settings
export interface AppSettings {
  feedingReminders: boolean;
  overdueReminders: boolean;
  openaiApiKey?: string; // BYOK - stored locally or __secure_storage__ flag
  expoDemoMode?: boolean;
  publicBaseUrl?: string; // Optional base URL for copied share links
}

export const DEFAULT_SETTINGS: AppSettings = {
  feedingReminders: true,
  overdueReminders: true,
};

// AI Assistant types
export interface AIMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

// Constants for UI
export const SUPPLEMENT_OPTIONS: { value: Supplement; label: string }[] = [
  { value: 'calcium', label: 'Calcium' },
  { value: 'd3', label: 'D3' },
  { value: 'multivitamin', label: 'Multivitamin' },
];

export const BREEDING_STATUS_OPTIONS: { value: BreedingStatus; label: string }[] = [
  { value: 'pet', label: 'Pet' },
  { value: 'breeder', label: 'Breeder' },
  { value: 'hold', label: 'Hold' },
];

export const PAIRING_STATUS_OPTIONS: { value: PairingStatus; label: string }[] = [
  { value: 'planned', label: 'Planned' },
  { value: 'active', label: 'Active' },
  { value: 'completed', label: 'Completed' },
  { value: 'cancelled', label: 'Cancelled' },
];
